# Generated by Django 4.1.2 on 2023-03-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_userimage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userimage',
            old_name='user',
            new_name='u1',
        ),
        migrations.AlterField(
            model_name='userimage',
            name='image',
            field=models.ImageField(default='abc.jpg', upload_to='User.user+"/"+User.email+"/"'),
        ),
    ]
